import { montserrat } from '@/fonts/fonts';
import 'modern-normalize/modern-normalize.css';
import '@/styles/global.scss';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html className={montserrat.className} lang="uk">
			<body>
				<main className="main">{children}</main>
			</body>
		</html>
	);
}
